services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comments
    ports:
      - "5666:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: